const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="rehmanrajpoot644@gmail.com"
global.location="Rawalpindi,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/Bootu-786/PRINCE-HACKER";
global.gurl  =process.env.GURL  || "https://api.whatsapp.com/send?phone=+923145269482";
global.website=process.env.GURL || "https://api.whatsapp.com/send?phone=+923145269482" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "null" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "POWERED BY PRINCE" 


global.devs = "923145269482" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923145269482";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "true"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "true"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "null";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_08_32_07_15_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzIsXG4gICAgICAgIDk3LFxuICAgICAgICAxODMsXG4gICAgICAgIDg2LFxuICAgICAgICAxNjQsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMzYsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTg1LFxuICAgICAgICA5NCxcbiAgICAgICAgMTc5LFxuICAgICAgICA2NixcbiAgICAgICAgNzAsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjA4LFxuICAgICAgICA2MyxcbiAgICAgICAgMzAsXG4gICAgICAgIDIzMSxcbiAgICAgICAgNCxcbiAgICAgICAgMjUzLFxuICAgICAgICA0MSxcbiAgICAgICAgMjMyLFxuICAgICAgICAxMyxcbiAgICAgICAgNDIsXG4gICAgICAgIDk4LFxuICAgICAgICAyMyxcbiAgICAgICAgMTQzLFxuICAgICAgICAyMDUsXG4gICAgICAgIDI2LFxuICAgICAgICAyNTAsXG4gICAgICAgIDIxNCxcbiAgICAgICAgOTZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjIsXG4gICAgICAgIDQ3LFxuICAgICAgICAxMDAsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjQzLFxuICAgICAgICAyMTIsXG4gICAgICAgIDE5LFxuICAgICAgICAyNTMsXG4gICAgICAgIDM2LFxuICAgICAgICAzMSxcbiAgICAgICAgMTMyLFxuICAgICAgICAxOSxcbiAgICAgICAgMTQ4LFxuICAgICAgICAyMTUsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTY4LFxuICAgICAgICAxMTksXG4gICAgICAgIDE3MyxcbiAgICAgICAgNyxcbiAgICAgICAgODEsXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTg3LFxuICAgICAgICA1NSxcbiAgICAgICAgNTQsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTMxLFxuICAgICAgICAxOTcsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMjMwLFxuICAgICAgICA4OSxcbiAgICAgICAgMTAxLFxuICAgICAgICAyNlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAwLFxuICAgICAgICAzMyxcbiAgICAgICAgMjExLFxuICAgICAgICA2LFxuICAgICAgICA5NyxcbiAgICAgICAgMzYsXG4gICAgICAgIDIzNyxcbiAgICAgICAgMTIwLFxuICAgICAgICAyNCxcbiAgICAgICAgOTMsXG4gICAgICAgIDEwMixcbiAgICAgICAgMTY1LFxuICAgICAgICAxNzMsXG4gICAgICAgIDg5LFxuICAgICAgICAxNjEsXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTM0LFxuICAgICAgICAxNjcsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTQ3LFxuICAgICAgICAyMDAsXG4gICAgICAgIDgxLFxuICAgICAgICA4OCxcbiAgICAgICAgODQsXG4gICAgICAgIDU3LFxuICAgICAgICA4MSxcbiAgICAgICAgMjA1LFxuICAgICAgICA2MSxcbiAgICAgICAgNDEsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjU1LFxuICAgICAgICA3NlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNixcbiAgICAgICAgMTkxLFxuICAgICAgICAyNDYsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTcwLFxuICAgICAgICAyLFxuICAgICAgICA5NCxcbiAgICAgICAgODgsXG4gICAgICAgIDQzLFxuICAgICAgICAxODksXG4gICAgICAgIDM4LFxuICAgICAgICAxMjMsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMjIsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTM1LFxuICAgICAgICAyMzYsXG4gICAgICAgIDEyLFxuICAgICAgICAxOSxcbiAgICAgICAgMjQ3LFxuICAgICAgICAxNTcsXG4gICAgICAgIDM2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDIxLFxuICAgICAgICA1OCxcbiAgICAgICAgNjYsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTg5LFxuICAgICAgICAxODEsXG4gICAgICAgIDE5NixcbiAgICAgICAgNjksXG4gICAgICAgIDEwM1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNzIsXG4gICAgICAgIDg3LFxuICAgICAgICAxOTksXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjE4LFxuICAgICAgICAyMzYsXG4gICAgICAgIDg4LFxuICAgICAgICAyMjMsXG4gICAgICAgIDE3MixcbiAgICAgICAgMTE3LFxuICAgICAgICAxMzQsXG4gICAgICAgIDI1LFxuICAgICAgICA2NSxcbiAgICAgICAgNzUsXG4gICAgICAgIDQsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTEsXG4gICAgICAgIDE3LFxuICAgICAgICAyNDgsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMjQ4LFxuICAgICAgICA4LFxuICAgICAgICAzMCxcbiAgICAgICAgMjI2LFxuICAgICAgICA2MCxcbiAgICAgICAgMTAxLFxuICAgICAgICAxLFxuICAgICAgICAxMDEsXG4gICAgICAgIDE4MixcbiAgICAgICAgOTAsXG4gICAgICAgIDQyLFxuICAgICAgICA3OFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA4MCxcbiAgICAgICAgMjA4LFxuICAgICAgICAxOSxcbiAgICAgICAgMTIwLFxuICAgICAgICA1MyxcbiAgICAgICAgMjE0LFxuICAgICAgICAxMTksXG4gICAgICAgIDIwMCxcbiAgICAgICAgMTc3LFxuICAgICAgICAyMzUsXG4gICAgICAgIDQ5LFxuICAgICAgICAxMDEsXG4gICAgICAgIDg1LFxuICAgICAgICAxOTMsXG4gICAgICAgIDY5LFxuICAgICAgICAyMDksXG4gICAgICAgIDI0NSxcbiAgICAgICAgNjEsXG4gICAgICAgIDE0NCxcbiAgICAgICAgODUsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMjQ4LFxuICAgICAgICAyMjEsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjUxLFxuICAgICAgICA2LFxuICAgICAgICAyOSxcbiAgICAgICAgMjM2LFxuICAgICAgICAyMTYsXG4gICAgICAgIDYwLFxuICAgICAgICAxMjgsXG4gICAgICAgIDE5XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDMyLFxuICAgICAgICAgIDE2MixcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMTI3LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDE3MyxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgNjIsXG4gICAgICAgICAgMTY1LFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICA3NixcbiAgICAgICAgICAyNyxcbiAgICAgICAgICAxNTYsXG4gICAgICAgICAgMTUzLFxuICAgICAgICAgIDg0LFxuICAgICAgICAgIDEyNCxcbiAgICAgICAgICAxNTgsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAxOCxcbiAgICAgICAgICA3LFxuICAgICAgICAgIDgyXG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDU0LFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDYwLFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICAyMDEsXG4gICAgICAgICAgMzEsXG4gICAgICAgICAgMTQ4LFxuICAgICAgICAgIDQ4LFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDUyLFxuICAgICAgICAgIDEyMixcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgODQsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDcsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMjE2LFxuICAgICAgICAgIDE5MixcbiAgICAgICAgICA5MixcbiAgICAgICAgICA0MlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDU0LFxuICAgICAgICA4NSxcbiAgICAgICAgNCxcbiAgICAgICAgMzUsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTQxLFxuICAgICAgICAyMDgsXG4gICAgICAgIDMsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTM3LFxuICAgICAgICAyMDksXG4gICAgICAgIDEyMSxcbiAgICAgICAgNTEsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjM1LFxuICAgICAgICAxMjUsXG4gICAgICAgIDE3NixcbiAgICAgICAgMjQyLFxuICAgICAgICAxMDAsXG4gICAgICAgIDE2LFxuICAgICAgICA5NyxcbiAgICAgICAgMTY2LFxuICAgICAgICAyNTAsXG4gICAgICAgIDE5LFxuICAgICAgICAxMzEsXG4gICAgICAgIDE5MSxcbiAgICAgICAgMTY0LFxuICAgICAgICA1MSxcbiAgICAgICAgMjksXG4gICAgICAgIDYyLFxuICAgICAgICAxMDQsXG4gICAgICAgIDIzMCxcbiAgICAgICAgNDAsXG4gICAgICAgIDg2LFxuICAgICAgICA2MSxcbiAgICAgICAgMTA3LFxuICAgICAgICA1LFxuICAgICAgICAxMjQsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTE3LFxuICAgICAgICAxNzAsXG4gICAgICAgIDQ4LFxuICAgICAgICA0MCxcbiAgICAgICAgMTAzLFxuICAgICAgICAyMTcsXG4gICAgICAgIDgwLFxuICAgICAgICAyNTAsXG4gICAgICAgIDQzLFxuICAgICAgICA2MyxcbiAgICAgICAgMjE2LFxuICAgICAgICAxMzAsXG4gICAgICAgIDEsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTgwLFxuICAgICAgICAyMDgsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMjA5LFxuICAgICAgICAyMDksXG4gICAgICAgIDMxLFxuICAgICAgICA3OSxcbiAgICAgICAgMTIxLFxuICAgICAgICAyNTQsXG4gICAgICAgIDE4NSxcbiAgICAgICAgMTM1XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAyNTAsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiVE9LY21CTU0yUjFrN0ZUdmdpdzRGaGNuRGNOQnlPWXF5MUVuUVhPMFpWRT1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjM0MTUyOTc0MDRAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjNGNkNCMTNCNzg0MUI4M0UzNjk5MUZGODg1NkVGNDZDXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMTAzMjMxNVxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzQxNTI5NzQwNEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNENFREQ3NURENUNFMjM1RDA3N0VENjIzMjU4RDVFQUFcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzIxMDMyMzE4XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzNDE1Mjk3NDA0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJDMUMyMkYwRUIyNkE5QzdCNDEzOUFENjFGODQ3RENGQ1wiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjEwMzIzMTlcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MjM0MTUyOTc0MDRAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkY5MjhBQjJDNUZGNkQwQjEwQTNGNTc4NzVBNjI4RkI0XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMTAzMjMxOVxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCIxWmFVZ3FaeFM2bTlDQUNzSnFZbFpRXCIsXG4gIFwicGhvbmVJZFwiOiBcIjUzMTIzNTRiLTk4MzAtNDg1My04ZjY4LTAwYTIwNjk4MjI4NFwiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMjMsXG4gICAgICAyLFxuICAgICAgNDYsXG4gICAgICAyMTIsXG4gICAgICAyMDYsXG4gICAgICA1NixcbiAgICAgIDIyOCxcbiAgICAgIDEyNixcbiAgICAgIDc2LFxuICAgICAgOTcsXG4gICAgICA1OCxcbiAgICAgIDU3LFxuICAgICAgNjQsXG4gICAgICAyMjEsXG4gICAgICAyMTYsXG4gICAgICAxOTIsXG4gICAgICAyMCxcbiAgICAgIDk2LFxuICAgICAgNDQsXG4gICAgICAxMzJcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0ZXJlZFwiOiBmYWxzZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDI1MSxcbiAgICAgIDI0MyxcbiAgICAgIDEwNixcbiAgICAgIDEzNyxcbiAgICAgIDQwLFxuICAgICAgMTksXG4gICAgICAxMTcsXG4gICAgICAxNzgsXG4gICAgICAyLFxuICAgICAgMzcsXG4gICAgICAxNCxcbiAgICAgIDE0NixcbiAgICAgIDk3LFxuICAgICAgMjA2LFxuICAgICAgNjgsXG4gICAgICAxMTIsXG4gICAgICAxMzYsXG4gICAgICAyMjIsXG4gICAgICAxMTgsXG4gICAgICAxMFxuICAgIF1cbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25cIjoge30sXG4gIFwiYWNjb3VudFwiOiB7XG4gICAgXCJkZXRhaWxzXCI6IFwiQ0xLNy9mVUdFUGE4MDdRR0dBRWdBQ2dBXCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlS2V5XCI6IFwiWmRjU2tlQkFvV3hsQ3l1bHN1UXBTWFNSV1JEQ0FCajk3VFJESzVlMjdCST1cIixcbiAgICBcImFjY291bnRTaWduYXR1cmVcIjogXCJ5bmk0RmI3UGoweVN3Y3Z0eGRhU3pyblNvSmF2cjU5QXM4UEVSbXM5alpsYmt1U3BzeVpoODVaVkNtSzFFaVQ3ZmdLZEtWSHJNM0ZBWWtFRE8yTFFBZz09XCIsXG4gICAgXCJkZXZpY2VTaWduYXR1cmVcIjogXCI5QzdWZ2hLUEc2aDltblhvU0hSbHJVQnh1RlR4Szl0VWREQ1NvRjIwOEQwSVEvd0luelc0eEplZmNVZC9lM3V5bkdqdXJYSkhNaUJqclcrcTFXVDdndz09XCJcbiAgfSxcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzQxNTI5NzQwNDo0QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIyNzI5MTk4NzE2NDc4NzM6NEBsaWRcIixcbiAgICBcIm5hbWVcIjogXCJQUk9HUkFNTUVSXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5MjM0MTUyOTc0MDQ6NEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAyMTUsXG4gICAgICAgICAgMTgsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICA2NCxcbiAgICAgICAgICAxNjEsXG4gICAgICAgICAgMTA4LFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICAxMSxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMTc4LFxuICAgICAgICAgIDIyOCxcbiAgICAgICAgICA0MSxcbiAgICAgICAgICA3MyxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMTQ1LFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDE2LFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAwLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDI1MyxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgNTIsXG4gICAgICAgICAgNjcsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgMTUxLFxuICAgICAgICAgIDE4MixcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMThcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyMTAzMjMxMyxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQUVwMFwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBRXAwLmpzb24iOiAie1wia2V5RGF0YVwiOlwiK29XK0RNUG0rSzNLUmQ2MmRTNzd3em9ZWjFRcUNKcGQ5cXpocjJldU1xOD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxODU4MDM1MTIyLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjEwMzIzMTM0NzVcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: PRINCE Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || "$",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 POWERED BY PRINCE 』```",
 
  author : process.env.PACK_AUTHER|| "PRINCE",
  packname: process.env.PACK_NAME || "PRINCE",
  botname : process.env.BOT_NAME  || "PRINCE",
  ownername:process.env.OWNER_NAME|| "PRINCE",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "PRINCE"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "true",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "true",
  //save_status: process.env.AUTO_SAVE_STATUS || "true",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
